version: '3.7'
services:
# centos7 apache2.4.*(http2)
  web:
    build: ./web
    container_name: lamp-web
    ports:
      - '443:443'
    volumes:
      - ./code:/var/www/html
      - ./web/logs:/var/log/httpd
      - cert:/etc/ssl/private
    restart: always
    env_file: .env
# php-fpm 7.4
  php:
    build: ./php
    container_name: lamp-php
    ports:
      - '9000'
    volumes:
      - ./code:/var/www/html
      - ./php/logs:/var/log/xdebug
    restart: always
    env_file: .env
# mariaDB
  db:
    build: ./db
    container_name: lamp-db
    restart: always
    env_file: .env
    ports:
      - 3306:3306
    volumes:
      - ./db/logs:/var/log/mysql
      - datastore:/var/lib/mysql
# phpMyadmin
  phpmyadmin:
    container_name: lamp-phpmyadmin
    image: phpmyadmin/phpmyadmin
    env_file: .env
    ports:
      - 8080:80
    depends_on:
      - db
# node js (include gulp)
  node:
    build: ./node
    container_name: lamp-node
    restart: always
    tty: true
    environment:
      - NODE_ENV=production
    ports:
      - '3000:3000'
    volumes:
      - ./code:/var/www/html
    depends_on:
      - web
# redis server
  redis:
    build: ./redis
    container_name: lamp-redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - "./redis/data:/data"
      - "./redis/logs:/var/log/redis"
volumes:
  cert:
  datastore:
